# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Management for Biologists
description:      'Surveying the hidden parts of the data life cycle'
url:              http://ericlind.github.io/data-mgmt-4-biologists
baseurl:          /data-mgmt-4-biologists
email:            elind@umn.edu
feedbackurl:      
author:
  name:           'Ethan White'
  url:            https://twitter.com/ethanwhite

github:
  repo:           https://github.com/datacarpentry/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
